---
title: "Lectures"
author: "Brian J. Smith"
---

| Date     | Lecture                                                           |
|:---------|:------------------------------------------------------------------|
|1/15/2026 |[Lecture 1: Introduction](lectures/01_intro.qmd)                   |
|1/20/2026 |[Lecture 2: Computing Basics](lectures/02_computing.qmd)           |
|1/22/2026 |[Lecture 3: Literate Programming](lectures/03_literate.qmd)        |
|1/27/2026 |[Lecture 4: Data Visualization: What and Why](lectures/04_what_why.qmd) | 
|1/29/2026 |[Lecture 5: Image Formats](lectures/05_image_formats.qmd)          | 
|2/3/2026  |[Lecture 6: Data Abstraction](lectures/06_abstract.qmd)            | 
|2/5/2026  |[Lecture 7: Data Wrangling](lectures/07_wrangling.qmd)             | 
|2/10/2026 | No class                                                          | 
|2/12/2026 | No class                                                          | 
|2/17/2026 |[Lecture 8: Marks and Channels](lectures/08_marks_channels.qmd)    | 
|2/19/2026 |[Lecture 9: `ggplot2`](lectures/09_ggplot2.qmd)                    | 
|2/24/2026 |[Lecture 10: Arranging Tables](lectures/10_tables.qmd)             | 
|3/3/2026  |[Lecture 11: Rules of Thumb](lectures/11_rules.qmd)                |
|3/5/2026  |[Lecture 12: Multiple Views](lectures/12_views.qmd)                | 
|3/24/2026 |[Lecture 13: Color](lectures/13_color.qmd)                         | 
|3/26/2026 |[Lecture 14: Reducing Items and Attributes](lectures/14_reduce.qmd)| 
|3/31/2026 |[Lecture 15: Embedding](lectures/15_embed.qmd)                     | 
|4/2/2026  |[Lecture 16: Surveys](lectures/16_surveys.qmd)                     | 



