---
title: "Assignment 5: Multi-panel Figures"
author: "Brian J. Smith"
date: "5 March 2026"
---

## Description

This assignment is to gain practice creating multi-panel figures. It is due March 12.

## Document Setup

For this assignment, create an HTML document using Quarto. You can refer to the [homepage.qmd](https://github.com/bsmity13/BCB5200/blob/main/code/homepage.qmd) document we created in class for some ideas.

- Make sure your YAML header has:
  - The option `embed-resources: true`
    - This goes under the html: format option.
    - It will make sure the HTML file stands alone, rather than referring to an external figure. I won't be able to see your figure if you upload and HTML file without this option.
- I want to see the code chunks that create your figure, so make sure you use `#| echo: true` in your R code chunk.
  - You may use code folding (`#| code-fold: true`) if you'd like.
    
## Instructions

1. Find a dataset.
2. Write a *small* amount of narrative in your Quarto document about the dataset and why you want to make a particular visualization. *Don't spend a lot of time on the narrative.*
3. Create a multi-panel figure either by:
  i. Using base R `par()` or `layout()` to arrange the panels, or
  ii. Using `patchwork` to arrange `ggplot2` panels.
  
*I.e.*, don't just use `ggplot2::facet_*()` to create panels.

Let me know if you have any questions!